# pylint: disable=unused-wildcard-import,wildcard-import,unused-import,wrong-import-position,C0302
"""
Smarter base settings module, shared by all environments.

This module provides the base Django settings for all Smarter environments.
For strongly-typed, project-specific settings overrides, see ``smarter_settings``.

Notes:

- Generated by ``django-admin startproject`` using Django 5.0.2.
- For more information on this file, see the `Django settings topic guide <https://docs.djangoproject.com/en/5.0/topics/settings/>`_.
- For the full list of settings and their values, see the `Django settings reference <https://docs.djangoproject.com/en/5.0/ref/settings/>`_.
"""

import ast
import hashlib
import logging
import logging.config
import math
import os
import re
import secrets
import subprocess
import sys
import time
import urllib.parse
from datetime import datetime
from pathlib import Path

from corsheaders.defaults import default_headers
from dotenv import load_dotenv

from smarter.__version__ import __version__ as smarter_version
from smarter.common.conf import smarter_settings
from smarter.common.helpers.console_helpers import formatted_text, formatted_text_green
from smarter.lib import json

logger = logging.getLogger(__name__)
logger_prefix = formatted_text(__name__)

load_dotenv()

logger.debug("%s Smarter version: %s", logger_prefix, smarter_version)


# pylint: disable=W0621
def smart_cast(value, default_value):
    """
    Cast string value to the same data type as the type.

    of the default_value. This is used for casting
    environment variable strings to the
    appropriate settings type.
    """
    if isinstance(default_value, bool):
        return str(value).lower() in ("1", "true", "yes", "on")
    if isinstance(default_value, int):
        try:
            return int(value)
        except ValueError:
            return default_value
    if isinstance(default_value, float):
        try:
            return float(value)
        except ValueError:
            return default_value
    if isinstance(default_value, list):
        # Try JSON, fallback to comma-separated
        try:
            parsed = ast.literal_eval(value)
            if isinstance(parsed, list):
                return parsed
        # pylint: disable=broad-except
        except Exception:
            pass
        return [item.strip() for item in value.split(",") if item.strip()]
    if isinstance(default_value, dict):
        try:
            parsed = ast.literal_eval(value)
            if isinstance(parsed, dict):
                return parsed
        # pylint: disable=broad-except
        except Exception:
            pass
        return default_value
    return value  # str or fallback


APPEND_SLASH = True
ALLOWED_HOSTS = smarter_settings.allowed_hosts
"""
A list of strings representing the host/domain names that this Django site can serve.

Smarter implements its own middleware to validate host names.
See smarter.apps.llm_client.middleware.security.SmarterSecurityMiddleware.

See:

    - https://docs.djangoproject.com/en/stable/ref/settings/#allowed-hosts
    - smarter_settings.allowed_hosts
"""

LOCAL_HOSTS = smarter_settings.local_hosts
"""
Supplemental list of local host/domain names that this Django site can serve.

This is specicific to Smarter and not officially part of Django settings.

See: smarter_settings.local_hosts
"""

# to disable redis/celery in collectstatic
if "collectstatic" in sys.argv:
    CELERY_TASK_ALWAYS_EAGER = True

CORS_ORIGIN_ALLOW_ALL = False
"""
A boolean that determines whether to allow all origins to make cross-site HTTP requests.

Smarter defaults this to False and uses CORS_ALLOWED_ORIGIN_REGEXES to restrict allowed origins.
See smarter.lib.django.middleware.cors.SmarterCorsMiddleware.

This affects the Access-Control-Allow-Origin header in responses to cross-site requests. It
affects the behavior for smarter-prompt React frontend applications making requests to the Smarter API.

Modifications to this will require comensurate changes to the CORS headers sent by
a Smarter Prompt host (e.g. AWS CloudFront distribution) to avoid CORS errors in browsers.

See `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-api-key",
    "accept-encoding",
    "dnt",
    "origin",
]
"""
A list of non-standard HTTP headers that are allowed in cross-site HTTP requests.

Smarter
Prompt frontends pass the Smarter API key in the 'x-api-key' header.

See `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CORS_ALLOW_CREDENTIALS = True
"""
A boolean that determines whether to allow cookies to be included in cross-site HTTP requests.

Smarter defaults this to True to allow session cookies to be sent by smarter-prompt React frontends.

See `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://[\w-]+\.(\d+-\d+-\d+)\.api\.localhost:\d+$",
    r"^https?://[\w-]+\.localhost:\d+$",
    r"^https?://[\w-]\.api\.localhost:\d+$",
]
"""
A list of regular expressions representing the origins that are allowed to make cross-site HTTP requests.

Smarter uses this setting to restrict allowed origins for CORS requests from smarter-prompt React frontends.

See `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CORS_ALLOWED_ORIGINS = []
"""
A list of origins that are allowed to make cross-site HTTP requests.

This is initialized here as an empty list
because base_aws.py and other environment-specific settings files will append to this list based on derived
settings values in smarter_settings.

See `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

# -------------------------------
# Cross Site Request Forgery (CSRF) settings
# -------------------------------
CSRF_COOKIE_SECURE = False
"""
A boolean that determines whether the CSRF cookie should be marked as "secure".

This is set to
False in base settings but **should** be set to True in production environments. Note that
there are challenges with setting this to True if the Smarter platform is behind a load balancer or
reverse proxy that terminates SSL.

See:

- `Django reference: <https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-secure>`__
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_COOKIE_NAME = "csrftoken"
"""
The name of the CSRF cookie.

Default is 'csrftoken'. This is a placeholder for Smarter-specific
functionality in smarter.lib.django.middleware.csrf.SmarterCsrfViewMiddleware.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-name
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_COOKIE_SAMESITE = "lax"
"""
The value for the SameSite flag on the CSRF cookie.

Default is 'Lax'. Smarters needs
this to be 'Lax' to support cross-site requests from smarter-prompt React frontends.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-samesite
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_COOKIE_AGE = 60 * 60 * 24
"""
The age of the CSRF cookie, in seconds.

Default is 60 * 60 * 24 (1 day). This is a placeholder
for Smarter-specific functionality in smarter.lib.django.middleware.csrf.SmarterCsrfViewMiddleware.
The default value should be sufficient for most use cases, unless your use case involves
e-commerce checkouts that need a shorter CSRF token lifetime.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-age
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_COOKIE_DOMAIN = smarter_settings.environment_platform_domain
"""
The domain to use for the CSRF cookie.

This is set to the Smarter platform domain derived
from smarter_settings.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-domain
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
- smarter_settings.environment_platform_domain
"""

CSRF_COOKIE_PATH = "/"
"""
The path to use for the CSRF cookie.

Default is '/'.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-path
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_COOKIE_HTTPONLY = False
"""
A boolean that determines whether the CSRF cookie should be marked as "HttpOnly".

Default is False
because the smarter-prompt React frontend needs to read the CSRF cookie value via JavaScript to
include it in the 'X-CSRFToken' header of HTTP requests.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-httponly
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"
"""
The name of the HTTP header that carries the CSRF token value.

Default is 'HTTP_X_CSRFTOKEN',
which corresponds to the 'X-CSRFToken' header sent by smarter-prompt React frontends.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-header-name
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_TRUSTED_ORIGINS = [
    smarter_settings.environment_platform_domain,
    smarter_settings.environment_api_domain,
]
"""
A list of trusted origins for cross-site request forgery protection.

This is initialized
here with the Smarter platform and API domains derived from smarter_settings.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-trusted-origins
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
- smarter_settings.environment_platform_domain
- smarter_settings.environment_api_domain
"""

CSRF_USE_SESSIONS = False
"""
A boolean that determines whether to store the CSRF token in the user session instead of.

a cookie. Default is False because smarter-prompt React frontends rely on the CSRF cookie.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-use-sessions
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

KNOX_TOKEN_MODEL = "knox.AuthToken"
"""
The Django model to use for Knox authentication tokens.

Smarter uses the default.
"""

# -------------------------------
# Django session settings
# -------------------------------
# Whether to set the flag restricting cookie leaks on cross-site requests.
# This can be 'Lax', 'Strict', 'None', or False to disable the flag.
SESSION_COOKIE_SAMESITE = "lax"
"""
The value for the SameSite flag on the session cookie.

Default is 'Lax'. Smarters needs
this to be 'Lax' to support cross-site requests from smarter-prompt React frontends.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-samesite
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

SESSION_COOKIE_SECURE = False
"""
A boolean that determines whether the session cookie should be marked as "secure".

This is set to
False in base settings but **should** be set to True in production environments. Note that
there are challenges with setting this to True if the Smarter platform is behind a load balancer or
reverse proxy that terminates SSL.

See:

- `Django reference: <https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-secure>`__
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

SESSION_COOKIE_NAME = "sessionid"
"""
The name of the session cookie.

Default is 'sessionid'. This is a placeholder for Smarter-specific
functionality in smarter.apps.prompt.views.PromptWorkbenchView.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-name
- `Smarter Prompt: <https://github.com/smarter-sh/smarter-prompt/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

SESSION_COOKIE_AGE = 1209600 * 2
"""
The age of the session cookie, in seconds.

Default is 1209600 (2 weeks).
"""

SESSION_COOKIE_DOMAIN = smarter_settings.environment_platform_domain
"""
The domain to use for the session cookie.

This is set to the Smarter platform domain derived
from smarter_settings.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-domain
- smarter_settings.environment_platform_domain
"""

SESSION_COOKIE_PATH = "/"
"""
The path to use for the session cookie.

Default is '/'. This is a placeholder.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-path
"""

SESSION_COOKIE_HTTPONLY = True
"""
A boolean that determines whether the session cookie should be marked as "HttpOnly".

Default is True.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-httponly
"""

SECURE_PROXY_SSL_HEADER = None
"""
A tuple representing a header/value combination that signifies a request is secure.

This is set to None in base settings
and **should** be set appropriately in production environments if the Smarter platform is behind
a load balancer or reverse proxy that terminates SSL.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#secure-proxy-ssl-header
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


BASE_DIR = Path(os.path.join(PROJECT_ROOT, "smarter")).resolve()

# -------------------------------
# Django storages settings for AWS S3
# -------------------------------
# See https://django-storages.readthedocs.io/en/latest/backends/amazon
if smarter_settings.aws_is_configured:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "access_key": (
                    smarter_settings.aws_access_key_id.get_secret_value()
                    if (
                        smarter_settings.aws_access_key_id
                        and getattr(smarter_settings.aws_access_key_id, "_secret_value", None) is not None
                    )
                    else None
                ),
                "secret_key": (
                    smarter_settings.aws_secret_access_key.get_secret_value()
                    if (
                        smarter_settings.aws_secret_access_key
                        and getattr(smarter_settings.aws_secret_access_key, "_secret_value", None) is not None
                    )
                    else None
                ),
                "bucket_name": smarter_settings.aws_s3_bucket_name,
                "region_name": smarter_settings.aws_region,
                "default_acl": "public-read",
                "querystring_auth": False,
                "custom_domain": smarter_settings.environment_cdn_domain,
            },
        }
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": "/home/smarter_user/data/media",
            },
        }
    }
STORAGES["staticfiles"] = {
    "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    "OPTIONS": {},
}
"""
The Django storages configuration for Smarter.

Uses AWS S3 if AWS is configured,
otherwise uses local filesystem storage.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#std:setting-STORAGES
"""

DEFAULT_FILE_STORAGE = smarter_settings.django_default_file_storage
"""
The default file storage backend for Django.

Uses AWS S3 if AWS is configured,
otherwise uses local filesystem storage. smarter_settings determines the appropriate
value based on whether or not it detects AWS authentication configuration in
the running environment.

See:

    - https://docs.djangoproject.com/en/5.0/ref/settings/#default-file-storage
    - smarter_settings.django_default_file_storage
"""

AWS_ACCESS_KEY_ID = (
    smarter_settings.aws_access_key_id.get_secret_value()
    if (
        smarter_settings.aws_access_key_id
        and getattr(smarter_settings.aws_access_key_id, "_secret_value", None) is not None
    )
    else None
)
"""
Supplemental setting for configuring AWS support.

The AWS access key ID
is retrieved and validated in smarter_settings.

For production deployments the chain of custody should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django AWS_ACCESS_KEY_ID.

See: smarter_settings.aws_access_key_id
"""

AWS_SECRET_ACCESS_KEY = (
    smarter_settings.aws_secret_access_key.get_secret_value()
    if (
        smarter_settings.aws_secret_access_key
        and getattr(smarter_settings.aws_secret_access_key, "_secret_value", None) is not None
    )
    else None
)
"""
Supplemental setting for configuring AWS support.

The AWS secret access key
is retrieved and validated in smarter_settings.

For production deployments the chain of custody should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django AWS_SECRET_ACCESS_KEY.

See: smarter_settings.aws_secret_access_key
"""

AWS_STORAGE_BUCKET_NAME = smarter_settings.aws_s3_bucket_name
"""
Supplemental setting for configuring AWS S3 storage support.

The S3 bucket name
is derived in smarter_settings.

See:

    - smarter_settings.aws_s3_bucket_name
"""

AWS_S3_REGION_NAME = smarter_settings.aws_region
"""
Supplemental setting for configuring AWS support.

The AWS region is
retrieved and validated in smarter_settings.

See:

    - smarter_settings.aws_region
"""

AWS_QUERYSTRING_AUTH = False  # disable querystring auth for public files
"""
Supplemental setting for configuring AWS S3 storage support.

Disables
querystring authentication for public files in favor of public-read ACL
that is configured in the Smarter Terraform scripts.

See:

- https://django-storages.readthedocs.io/en/latest/backends/amazon/#querystring-auth
- https://github.com/smarter-sh/smarter-infrastructure
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = (
    smarter_settings.secret_key.get_secret_value()
    if (smarter_settings.secret_key and getattr(smarter_settings.secret_key, "_secret_value", None) is not None)
    else None
)
"""
The secret key for this Django installation.

This is retrieved and validated
from smarter_settings. If not set, a random key is generated and logged as a warning.

For production deployments the chain of custody should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SECRET_KEY.

See:

    - https://docs.djangoproject.com/en/5.0/ref/settings/#secret-key
    - smarter_settings.secret_key
"""

if SECRET_KEY == smarter_settings.default_missing_value:
    random_string = secrets.token_urlsafe(64)
    random_bytes = random_string.encode("utf-8")
    hash_object = hashlib.sha256(random_bytes)
    SECRET_KEY = hash_object.hexdigest()
    logger.warning("SECRET_KEY not set. Using randomized value: %s", SECRET_KEY)

logger.debug("PROJECT_ROOT: %s", PROJECT_ROOT)
logger.debug("BASE_DIR: %s", BASE_DIR)
logger.debug("SECRET_KEY: %s", SECRET_KEY)


DEBUG = smarter_settings.debug_mode
"""
A boolean that turns on/off debug mode for Django.

This is retrieved
from smarter_settings.debug_mode.

See:

    - https://docs.djangoproject.com/en/5.0/ref/settings/#debug
    - smarter_settings.debug_mode
"""

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:smarter@smarter-redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

"""
The Django cache configuration for Smarter, using Redis as the cache backend.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#caches
- https://github.com/smarter-sh/smarter/blob/main/docker-compose.yml
- https://artifacthub.io/packages/helm/project-smarter/smarter
"""

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
"""
The Django session engine configuration for Smarter, using the cache backend.

(Redis) for session storage. Storing sessions in Redis will preserve user sessions
across multiple web server instances in a load-balanced environment, and also
insulates from sessions being lost due to redeployments or restarts of web server.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#session-engine
"""

# Default Celery Configuration
CELERY_BROKER_URL = "redis://:smarter@smarter-redis:6379/1"
"""
The Celery broker URL for Smarter, using Redis as the message broker.

See:

- https://docs.celeryq.dev/en/stable/getting-started/brokers/redis.html
- https://github.com/smarter-sh/smarter/blob/main/docker-compose.yml
- https://artifacthub.io/packages/helm/project-smarter/smarter
"""

CELERY_TASK_TIME_LIMIT = 30 * 60
"""
The maximum time limit (in seconds) for Celery tasks in Smarter.

Default is 30 minutes.
Smarter sets this primarily due to indeterminate AWS Route53 DNS resolution and propagation
times when deploying LLMClients/Agents.

See: https://docs.celeryq.dev/en/stable/userguide/configuration.html#std:setting-task_time_limit
"""

CELERY_WORKER_HIJACK_ROOT_LOGGER = False
"""
A Celery setting that prevents Celery workers from hijacking the root logger.

This is set to False
to allow Celery logs to be integrated with the overall Smarter logging configuration without interference.

See: https://docs.celeryq.dev/en/stable/userguide/configuration.html#std:setting-worker_hijack_root_logger
"""

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admindocs",
    "django.contrib.humanize",
    "django_hosts",
    "storages",
    # smarter apps
    # -------------------------------
    "smarter.lib.drf",
    "smarter.lib.journal",
    "smarter.apps.account",
    "smarter.apps.api",
    "smarter.apps.llm_client",
    "smarter.apps.connection",
    "smarter.apps.dashboard",
    "smarter.apps.docs",
    "smarter.apps.plugin",
    "smarter.apps.prompt",
    "smarter.apps.provider",
    "smarter.apps.secret",
    "smarter.apps.vectorstore",
    # 3rd party apps
    # -------------------------------
    "rest_framework",
    "knox",
    "taggit",
    "corsheaders",
    "drf_yasg",
    "django_celery_beat",
    "social_django",
    "waffle",
]

MIDDLEWARE = [
    # this is a diagnostic middleware used for local development and testing.
    # It enforces the return type of all middleware in the request chain.
    # It should be placed at the beginning of the chain to catch any issues
    # as early as possible.
    # "smarter.lib.django.middleware.debug.MiddlewareDebugMiddleware",
    # -------------------------------
    #
    "django_hosts.middleware.HostsRequestMiddleware",
    #
    # this replaces corsheaders.middleware.CorsMiddleware"
    "django.contrib.sessions.middleware.SessionMiddleware",
    # -------------------------------
    #
    #
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    #
    # replaces rest_framework.authentication.TokenAuthentication
    # for api-key token authentication. Adds waffle-switched enable,
    # and Django signals for logging context. This should be placed
    # near and after AuthenticationMiddleware
    # -------------------------------
    "smarter.lib.drf.middleware.SmarterTokenAuthenticationMiddleware",
    #
    #
    "waffle.middleware.WaffleMiddleware",
    #
    # to manage logging context by user. This has to run AFTER
    # authentication middleware so that it can get the user info for logging context.
    # -------------------------------
    "smarter.lib.logging.middleware.SmarterRequestLogContextMiddleware",
    #
    # handles cors for deployed llm_clients.
    # -------------------------------
    "smarter.lib.django.middleware.cors.SmarterCorsMiddleware",
    #
    # custom middleware that returns 400 responses for requests for common
    # sensitive files like .env, private key files, etc.
    # -------------------------------
    "smarter.lib.django.middleware.sensitive_files.SmarterBlockSensitiveFilesMiddleware",
    #
    # custom throttling middleware to block excessive 404 errors originating
    # from botnets probing for vulnerabilities.
    # -------------------------------
    "smarter.lib.django.middleware.excessive_404.SmarterBlockExcessive404Middleware",
    #
    # -------------------------------
    "django.middleware.common.CommonMiddleware",
    #
    #
    # this replaces django.middleware.csrf.SmarterCsrfViewMiddleware
    # to add llm_client-specific CSRF handling
    # -------------------------------
    "smarter.lib.django.middleware.csrf.SmarterCsrfViewMiddleware",
    #
    # -------------------------------
    # to manage ALLOWED_HOSTS
    # -------------------------------
    # this replaces django.middleware.security.SecurityMiddleware
    # simple middleware to block requests for common sensitive files
    # like .env, private key files, etc.
    # -------------------------------
    "smarter.apps.llm_client.middleware.security.SmarterSecurityMiddleware",
    #
    # -------------------------------
    # to handle 'already associated error from python social auth'
    # -------------------------------
    "smarter.apps.account.pipeline.SmarterSocialAuthExceptionMiddleware",
    #
    #
    ###########################################################################
    # Response middleware
    ###########################################################################
    #
    # compress static files and serve them with WhiteNoise.
    # -------------------------------
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_hosts.middleware.HostsResponseMiddleware",
    "smarter.lib.django.middleware.json.SmarterJsonErrorMiddleware",
    "smarter.lib.django.middleware.html_minify.HTMLMinifyMiddleware",
]

if smarter_settings.debug_mode and not "test" in sys.argv:
    INSTALLED_APPS += [
        "debug_toolbar",
    ]
    logger.debug(formatted_text_green("Debug mode is ON. debug_toolbar is added to INSTALLED_APPS."))

    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]
    logger.debug(formatted_text_green("Debug mode is ON. debug_toolbar middleware is enabled."))


ROOT_HOSTCONF = "smarter.hosts"
"""
The root host configuration module for django-hosts.

Smarter hosts multiple subdomains
for platform, API, and llm_client apps. These are defined in smarter.hosts.

See: https://django-hosts.readthedocs.io/en/latest/
"""

ROOT_URLCONF = "smarter.urls.console"
"""
The root URL configuration module for Smarter.

This points to smarter.urls.console,
which defines the URL patterns for the Smarter web platform console.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#root-urlconf
"""

DEFAULT_HOST = smarter_settings.platform_subdomain
"""
The default host name for django-hosts.

This is set to the Smarter platform subdomain.

See: https://django-hosts.readthedocs.io/en/latest/
"""

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "smarter.apps.account.context_processors.base",
                "smarter.apps.dashboard.context_processors.branding",
                "smarter.apps.dashboard.context_processors.static_version",
                "smarter.apps.dashboard.context_processors.base",
                "smarter.apps.dashboard.context_processors.footer",
                "smarter.apps.dashboard.context_processors.sidebar",
            ],
        },
    },
]

WSGI_APPLICATION = "smarter.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "smarter",
        "USER": "smarter",
        "PASSWORD": "smarter",
        "HOST": "smarter-mysql",  # Or an IP Address that your DB is hosted on
        "PORT": "3306",
    }
}
"""
The Django database configuration for Smarter, using MySQL as the database backend.

Smarter **should** be able to support other common Sql databases supported by Django
with minimal or no changes, but MySQL is the recommended and tested database backend.

This setting is environment specific and will typically be overridden in
smarter/smarter/settings/base_aws.py or other environment-specific settings files.

These credentials are created for you by the Smarter Terraform scripts when deploying
the Smarter platform.

For cloud deployments the chain of custody for database credentials should be:

Kubernetes Secret -> environment variable -> smarter_settings -> Django DATABASES.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#databases
- https://github.com/smarter-sh/smarter-infrastructure
"""

# https://python-social-auth.readthedocs.io/en/latest/configuration/django.html
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = os.environ.get("AUTHENTICATION_BACKENDS")
AUTHENTICATION_BACKENDS = (
    AUTHENTICATION_BACKENDS.split(",")
    if AUTHENTICATION_BACKENDS
    else [
        "social_core.backends.google.GoogleOAuth2",
        "social_core.backends.github.GithubOAuth2",
        "django.contrib.auth.backends.ModelBackend",
    ]
)
"""
The authentication backends for Smarter, including social authentication.

backends for Google, GitHub, and LinkedIn, as well as the default Django
model backend.

Note that Smarter additionally implements its own custom key-based REST API
authentication backend.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#authentication-backends
- https://docs.smarter.sh/en/latest/developers/architecture/lib/drf.html
"""

SOCIAL_AUTH_CREATE_USERS = False
"""
A boolean that determines whether to automatically create user accounts.

when a user authenticates via a social authentication provider.

IMPORTANT: Smarter defaults this to False for security reasons to prevent
what is effectively random virtually-anonymous user account creation via
social authentication. User accounts should be created via the Smarter
platform console by an administrator, then linked to social authentication
providers as needed.

SETTING THIS TO TRUE IS A SECURITY AND A FINANCIAL RISK BECAUSE IT
WILL ALLOW ANY USERS (E.G. BOTNETS) TO CREATE ACCOUNTS AND ACCESS PAID
SERVICES WITHOUT RESTRICTION OR OVERSIGHT.
"""

SOCIAL_AUTH_PIPELINE = (
    # Get the information we can about the user and return it in a simple
    # format to create the user instance later. On some cases the details are
    # already part of the auth response from the provider, but sometimes this
    # could hit a provider API.
    "social_core.pipeline.social_auth.social_details",
    # Get the social uid from whichever service we're authing thru. The uid is
    # the unique identifier of the given user in the provider.
    "social_core.pipeline.social_auth.social_uid",
    # Verifies that the current auth process is valid within the current
    # project, this is where emails and domains whitelists are applied (if
    # defined).
    "social_core.pipeline.social_auth.auth_allowed",
    # Checks if the current social-account is already associated in the site.
    "social_core.pipeline.social_auth.social_user",
    # Make up a username for this person, appends a random string at the end if
    # there's any collision.
    "social_core.pipeline.user.get_username",
    # Send a validation email to the user to verify its email address.
    # 'social_core.pipeline.mail.mail_validation',
    # Associates the current social details with another user account with
    # a similar email address.
    "social_core.pipeline.social_auth.associate_by_email",
    # Create a user account if we haven't found one yet.
    "smarter.apps.account.pipeline.create_user",
    # Create the record that associated the social account with this user.
    "social_core.pipeline.social_auth.associate_user",
    # Populate the extra_data field in the social record with the values
    # specified by settings (and the default ones like access_token, etc).
    "social_core.pipeline.social_auth.load_extra_data",
    # Update the user record with any changed info from the auth service.
    "smarter.apps.account.pipeline.user_details",
    # Custom: Redirect inactive accounts before finalizing login
    "smarter.apps.account.pipeline.redirect_inactive_account",
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = (
    smarter_settings.social_auth_google_oauth2_key.get_secret_value()
    if (
        smarter_settings.social_auth_google_oauth2_key
        and getattr(smarter_settings.social_auth_google_oauth2_key, "_secret_value", None) is not None
    )
    else None
)
"""
Python Social Auth Google OAuth2 client ID for Smarter.

The chain of custody for this secret should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_GOOGLE_OAUTH2_KEY.

See:

    - https://python-social-auth.readthedocs.io/en/latest/backends/google.html
    - smarter_settings.social_auth_google_oauth2_key
"""

SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = (
    smarter_settings.social_auth_google_oauth2_secret.get_secret_value()
    if (
        smarter_settings.social_auth_google_oauth2_secret
        and getattr(smarter_settings.social_auth_google_oauth2_secret, "_secret_value", None) is not None
    )
    else None
)
"""
Python Social Auth Google OAuth2 client secret for Smarter.

The chain of custody for this secret should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET.

See:

    - https://python-social-auth.readthedocs.io/en/latest/backends/google.html
    - smarter_settings.social_auth_google_oauth2_secret
"""

SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = urllib.parse.urljoin(
    smarter_settings.environment_url, "/social-auth/complete/google-oauth2/"
)
"""
The redirect URI for Google OAuth2 social authentication in Smarter.

Do not change this value unless you know what you are doing.

See:

    - https://python-social-auth.readthedocs.io/en/latest/backends/google.html
    - smarter_settings.environment_url
"""

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ["openid", "email", "profile"]
"""
The OAuth2 scopes for Google social authentication in Smarter.

See: https://python-social-auth.readthedocs.io/en/latest/backends/google.html
"""

SOCIAL_AUTH_GITHUB_KEY = (
    smarter_settings.social_auth_github_key.get_secret_value()
    if (
        smarter_settings.social_auth_github_key
        and getattr(smarter_settings.social_auth_github_key, "_secret_value", None) is not None
    )
    else None
)
"""
Python Social Auth GitHub OAuth2 client ID for Smarter.

The chain of custody for this secret should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_GITHUB_KEY.

See:

    - https://python-social-auth.readthedocs.io/en/latest/backends/github.html
    - smarter_settings.social_auth_github_key
"""

SOCIAL_AUTH_GITHUB_SECRET = (
    smarter_settings.social_auth_github_secret.get_secret_value()
    if (
        smarter_settings.social_auth_github_secret
        and getattr(smarter_settings.social_auth_github_secret, "_secret_value", None) is not None
    )
    else None
)
"""
Python Social Auth GitHub OAuth2 client secret for Smarter.

The chain of custody for this secret should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_GITHUB_SECRET.

See:

    - https://python-social-auth.readthedocs.io/en/latest/backends/github.html
    - smarter_settings.social_auth_github_secret
"""

SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = (
    smarter_settings.social_auth_linkedin_oauth2_key.get_secret_value()
    if (
        smarter_settings.social_auth_linkedin_oauth2_key
        and getattr(smarter_settings.social_auth_linkedin_oauth2_key, "_secret_value", None) is not None
    )
    else None
)
"""
Python Social Auth LinkedIn OAuth2 client ID for Smarter.

The chain of custody for this secret should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY.

See:

    - https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
    - smarter_settings.social_auth_linkedin_oauth2_key
"""
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = (
    smarter_settings.social_auth_linkedin_oauth2_secret.get_secret_value()
    if (
        smarter_settings.social_auth_linkedin_oauth2_secret
        and getattr(smarter_settings.social_auth_linkedin_oauth2_secret, "_secret_value", None) is not None
    )
    else None
)
"""
Python Social Auth LinkedIn OAuth2 client secret for Smarter.

NOTE: (Nov-2025) LinkedIn has deprecated OAuth2 client secrets for security reasons. The Smarter reference
cloud platform is no longer using LinkedIn OAuth2 for social authentication, but the configuration settings remain
here for backward compatibility with existing Smarter deployments that may still be using LinkedIn OAuth2.

The chain of custody for this secret should be:
GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET.

See:

    - https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
    - smarter_settings.social_auth_linkedin_oauth2_secret
"""

SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE = ["openid", "profile", "email"]
"""
The OAuth2 scopes for LinkedIn social authentication in Smarter.

NOTE: (Nov-2025) LinkedIn has deprecated OAuth2 client secrets for security reasons. The Smarter reference
cloud platform is no longer using LinkedIn OAuth2 for social authentication, but the configuration settings remain
here for backward compatibility with existing Smarter deployments that may still be using LinkedIn OAuth2.

See: https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
"""


SOCIAL_AUTH_LINKEDIN_OAUTH2_FIELD_SELECTORS = ["id", "first-name", "last-name", "email-address"]
"""
The OAuth2 field selectors for LinkedIn social authentication in Smarter.

NOTE: (Nov-2025) LinkedIn has deprecated OAuth2 client secrets for security reasons. The Smarter reference
cloud platform is no longer using LinkedIn OAuth2 for social authentication, but the configuration settings remain
here for backward compatibility with existing Smarter deployments that may still be using LinkedIn OAuth2.

See: https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
"""

SOCIAL_AUTH_LINKEDIN_OAUTH2_REDIRECT_URI = urllib.parse.urljoin(
    smarter_settings.environment_url, "/social-auth/complete/linkedin-oauth2/"
)
"""
The redirect URI for LinkedIn OAuth2 social authentication in Smarter.

NOTE: (Nov-2025) LinkedIn has deprecated OAuth2 client secrets for security reasons. The Smarter reference
cloud platform is no longer using LinkedIn OAuth2 for social authentication, but the configuration settings remain
here for backward compatibility with existing Smarter deployments that may still be using LinkedIn OAuth2.

Do not change this value unless you know what you are doing.

See:

    - https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
    - smarter_settings.environment_url
"""

SOCIAL_AUTH_LINKEDIN_OAUTH2_EXTRA_DATA = [
    ("id", "id"),
    ("firstName", "first_name"),
    ("lastName", "last_name"),
    ("emailAddress", "email_address"),
]
"""
The extra data fields to retrieve from LinkedIn during social authentication in Smarter.

NOTE: (Nov-2025) LinkedIn has deprecated OAuth2 client secrets for security reasons. The Smarter reference
cloud platform is no longer using LinkedIn OAuth2 for social authentication, but the configuration settings remain
here for backward compatibility with existing Smarter deployments that may still be using LinkedIn OAuth2.

See: https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
"""

SOCIAL_AUTH_ADMIN_USER_SEARCH_FIELDS = ["username", "first_name", "email"]
"""
The user fields that can be searched in the Django admin interface for social authentication users.

See: https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#admin-integration
"""

LOGIN_URL = "/login/"
"""
The URL to redirect users to for login.

Default is '/login/'. Do not change this
value unless you know what you are doing.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#login-url
"""

LOGIN_REDIRECT_URL = "/"
"""
The URL to redirect users to after successful login.

Default is '/'.
Do not change this value unless you know what you are doing.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#login-redirect-url
"""

LOGOUT_REDIRECT_URL = "/"
"""
The URL to redirect users to after logout.

Default is '/'.
Do not change this value unless you know what you are doing.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#logout-redirect-url
"""


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
"""
The password validation settings for Smarter, using Django's built-in.

password validators. These validators help ensure that user passwords
meet minimum security requirements. These rules should be sufficient
for most use cases, but can be customized as needed.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
"""

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = "en-us"
"""
The default language code for Smarter.

Default is 'en-us'.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#language-code
"""

TIME_ZONE = "UTC"
"""
The default time zone for Smarter.

Default is 'UTC'.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#time-zone
"""

USE_I18N = True
"""
A boolean that specifies whether Django's internationalization system.

should be enabled. Default is True. I18N support is important for
Smarter to support multiple languages and locales.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#use-i18n
"""

USE_TZ = True
"""
A boolean that specifies whether Django should use timezone-aware datetimes.

Default is True. Timezone support is important for Smarter to handle
date and time data correctly across different time zones.

timezone-aware datetimes help ensure that timestamps are accurate
and consistent regardless of the user's location. These were
released in Django 1.4 and are now standard practice for web applications.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#use-tz
"""


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = "/static/"
"""
The URL prefix for static files in Smarter.

Default is '/static/'. This values needs to
be consistent with the STATICFILES_DIRS and STATIC_ROOT settings, and also
needs to consider how the Dockerfile file system is structured for serving static files.

Do not change this value unless you know what you are doing.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#static-url
- https://github.com/smarter-sh/smarter/blob/main/Dockerfile
"""

STATIC_ROOT = PROJECT_ROOT / "staticfiles"
"""
The absolute file system path to the directory where static files will be collected.

This is set to the 'staticfiles' directory in the project root. This directory
is used by the 'collectstatic' management command to gather all static files
from the various Django apps and store them in a single location for serving.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#static-root
"""

STATICFILES_DIRS = [BASE_DIR / "static"]
"""
A list of directories where Django will also look for static files, in addition.

to each app's 'static' subdirectory. This is set to the 'static' directory
in the BASE_DIR. This allows for global static files that are not tied to
a specific app.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#staticfiles-dirs
"""

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
"""
The default primary key field type for Django models in Smarter.

This is set to 'BigAutoField', which
is a 64-bit integer that automatically increments. This is suitable for most use cases and provides
a large range of values for primary keys.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
"""

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "smarter.lib.drf.token_authentication.SmarterTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "smarter.lib.drf.parsers.YAMLParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}
"""
The Django REST Framework configuration for Smarter, including default authentication classes,.

permission classes, and parser classes.

Do not change these values unless you know what you are doing. Even then, it's probably a bad idea.

See: https://www.django-rest-framework.org/api-guide/settings/
"""

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s - %(levelname)s - %(processName)s - %(message)s",
            "datefmt": "[%Y-%m-%d %H:%M:%S %z]",
        },
        "truncated": {
            "format": "%(asctime)s %(levelname)s %(message)s",
            "datefmt": "[%Y-%m-%d %H:%M:%S]",
        },
    },
    "filters": {
        "health_check": {
            "()": "smarter.lib.logging.filters.HealthCheckFilter",
        },
    },
    "handlers": {
        "default": {
            "level": smarter_settings.log_level_name,
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "uvicorn": {
            "level": logging.INFO,
            "class": "logging.StreamHandler",
            "formatter": "truncated",
            "filters": ["health_check"],
        },
        "redis": {
            "level": logging.INFO,
            "class": "smarter.lib.logging.RedisLogHandler",
            "formatter": "truncated",
        },
    },
    "root": {
        "handlers": ["default", "redis"],
        "level": smarter_settings.log_level_name,
    },
    "loggers": {
        "uvicorn.access": {
            "handlers": ["uvicorn"],
            "level": logging.INFO,
            "propagate": False,
        },
        "celery": {
            "level": smarter_settings.log_level_name,
            "propagate": True,
        },
        "celery.task": {
            "level": smarter_settings.log_level_name,
            "propagate": True,
        },
    },
}
"""
Comprehensive logging configuration for the Smarter platform.

This dictionary configures Python's built-in logging system for the Smarter
application. It defines log formatters, handlers, filters, and loggers to
control how log messages are processed and where they are sent.

Formatters
----------
verbose
    Includes timestamp, log level, process name, and message. Used for detailed logs.
truncated
    Shorter format with timestamp, log level, and message. Used for Redis logs.

Filters
-------
health_check
    Uses :class:`smarter.lib.logging.filters.HealthCheckFilter` to suppress log entries
    for health check endpoints (e.g., /healthz/, /readiness/).

Handlers
--------
default
    Console handler (logging.StreamHandler) for standard output. Uses the 'verbose'
    formatter and applies the health_check filter. Log level is set by
    ``smarter_settings.log_level_name``.
redis
    Custom handler (:class:`smarter.lib.logging.RedisLogHandler`) for sending logs
    to Redis. Uses the 'truncated' formatter and applies the health_check filter.
    Log level is hardcoded to INFO.

Root Logger
-----------
Handlers: ['default', 'redis']
Level: Set by ``smarter_settings.log_level_name``
All log messages are sent to both the console and Redis unless filtered out.

Loggers
-------
celery, celery.task
    Both propagate to the root logger and use the same log level as the rest
    of the application.

Log Level
---------
The log level for all handlers and loggers is dynamically set by
``smarter_settings.log_level_name`` (e.g., 'INFO', 'DEBUG', 'WARNING').

References
----------
- Django logging documentation: https://docs.djangoproject.com/en/5.0/topics/logging/
- Python logging documentation: https://docs.python.org/3/library/logging.config.html#logging-config-dictschema

This configuration ensures that health check requests do not clutter logs, and
that logs are available both in the console and in Redis for further processing
or monitoring.
"""

logging.config.dictConfig(LOGGING)

# https://dj-stripe.dev/dj-stripe/2.7/installation/
STRIPE_LIVE_SECRET_KEY = (
    smarter_settings.stripe_live_secret_key.get_secret_value()
    if (
        smarter_settings.stripe_live_secret_key
        and getattr(smarter_settings.stripe_live_secret_key, "_secret_value", None) is not None
    )
    else ""
)
STRIPE_TEST_SECRET_KEY = (
    smarter_settings.stripe_test_secret_key.get_secret_value()
    if (
        smarter_settings.stripe_test_secret_key
        and getattr(smarter_settings.stripe_test_secret_key, "_secret_value", None) is not None
    )
    else ""
)
STRIPE_LIVE_MODE = False  # Change to True in production
DJSTRIPE_WEBHOOK_SECRET = (
    "whsec_xxx"  # Get it from the section in the Stripe dashboard where you added the webhook endpoint
)
DJSTRIPE_USE_NATIVE_JSONFIELD = True  # We recommend setting to True for new installations
DJSTRIPE_FOREIGN_KEY_TO_FIELD = "id"

SMTP_SENDER = smarter_settings.smtp_sender
"""
The default sender email address for outgoing emails from Smarter.

This is derived from smarter_settings.

See:

    - https://docs.djangoproject.com/en/5.0/topics/email/
    - smarter_settings.smtp_sender
"""

SMTP_FROM_EMAIL = smarter_settings.smtp_from_email
"""
The default "from" email address for outgoing emails from Smarter.

This is derived from smarter_settings.

See:

    - https://docs.djangoproject.com/en/5.0/topics/email/
    - smarter_settings.smtp_from_email
"""

SMTP_HOST = smarter_settings.smtp_host
"""
The SMTP host for outgoing emails from Smarter.

This is derived from smarter_settings.

See:
    - https://docs.djangoproject.com/en/5.0/topics/email/
    - smarter_settings.smtp_host
"""

SMTP_PASSWORD = (
    smarter_settings.smtp_password.get_secret_value()
    if (smarter_settings.smtp_password and getattr(smarter_settings.smtp_password, "_secret_value", None) is not None)
    else None
)
"""
The SMTP password for outgoing emails from Smarter.

This is derived from smarter_settings.
When using AWS SES as the SMTP service, this is the SMTP password generated from the AWS SES console.
Note that this is NOT the AWS secret access key, nor is it the AWS IAM user password.

This credential is created for you when using the Smarter Terraform scripts to deploy
the Smarter cloud platform with AWS SES as the SMTP service.

For production deployments the chain of custody should be:

Kubernetes Secret -> environment variable -> smarter_settings -> Django SMTP_PASSWORD.

See:

    - https://docs.djangoproject.com/en/5.0/topics/email/
    - https://github.com/smarter-sh/smarter-infrastructure
    - smarter_settings.smtp_password
"""

SMTP_PORT = smarter_settings.smtp_port
"""
The SMTP port for outgoing emails from Smarter.

This is derived from smarter_settings.

See:
    - https://docs.djangoproject.com/en/5.0/topics/email/
    - smarter_settings.smtp_port
"""

SMTP_USE_SSL = smarter_settings.smtp_use_ssl
"""
A boolean that specifies whether to use SSL for SMTP connections in Smarter.

This is derived from smarter_settings.

See:

    - https://docs.djangoproject.com/en/5.0/topics/email/
    - smarter_settings.smtp_use_ssl
"""

SMTP_USE_TLS = smarter_settings.smtp_use_tls
"""
A boolean that specifies whether to use TLS for SMTP connections in Smarter.

This is derived from smarter_settings.

See:
    - https://docs.djangoproject.com/en/5.0/topics/email/
    - smarter_settings.smtp_use_tls
"""

SMTP_USERNAME = (
    smarter_settings.smtp_username.get_secret_value()
    if (smarter_settings.smtp_username and getattr(smarter_settings.smtp_username, "_secret_value", None) is not None)
    else None
)
"""
The SMTP username for outgoing emails from Smarter.

This is derived from smarter_settings.
When using AWS SES as the SMTP service, this is the SMTP password generated from the AWS SES console.
Note that this is NOT the AWS secret access key, nor is it the AWS IAM user password.

This credential is created for you when using the Smarter Terraform scripts to deploy
the Smarter cloud platform with AWS SES as the SMTP service.

For production deployments the chain of custody should be:

Kubernetes Secret -> environment variable -> smarter_settings -> Django SMTP_PASSWORD.

See:

    - https://docs.djangoproject.com/en/5.0/topics/email/
    - https://github.com/smarter-sh/smarter-infrastructure
    - smarter_settings.smtp_username
"""

TAGGIT_CASE_INSENSITIVE = True
"""If True, makes taggit tags case insensitive."""

TAGGIT_STRIP_UNICODE_WHEN_SLUGIFYING = True
"""If True, strips unicode characters when slugifying tags."""

WAFFLE_CREATE_MISSING_SWITCHES = True
"""
If True, enables automatic creation of missing waffle switches in the database during deployment.

jobs. This is intended to simplify management of waffle switches in Smarter deployments.
"""

# Reverse the default case-sensitive handling of tags
TAGGIT_CASE_INSENSITIVE = os.environ.get("TAGGIT_CASE_INSENSITIVE", "True").lower() in ("true", "1", "t", "yes")
"""
A boolean that specifies whether to make taggit tags case insensitive. This is.

derived from the environment variable "TAGGIT_CASE_INSENSITIVE", which defaults
to "True". If set to True, tags will be treated as case insensitive
(e.g. "Tag" and "tag" will be considered the same tag).
"""

WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds


# step 2: load environment variables from .env file (if present)
ASCII_CONTROL_CHAR_REGEX = re.compile(r"[\x00-\x1F\x7F]")
"""
Process environment variables to override settings values.

This allows for 12-factor style configuration via environment variables.
Environment variable values are cast to the same data type as the
existing Django or Smarter setting value.

The basic process is:

1. Set default settings values.
2. Load environment variables from a .env file (if present) and os.environ.
3. Map environment variables to Django settings by removing the ``DJANGO_``
   prefix. For any environment variable that matches an existing Django
   setting, cast the value to the same type as the existing setting value
   and override the default.

   For anything else, analyze the passed value to infer the intended data
   type and create a new setting if it does not already exist.

Note:
Django settings are prefixed with ``DJANGO_`` and Smarter settings
are prefixed with ``SMARTER_``.
"""

# step 3: override settings from environment variables
if any(key.startswith("DJANGO_") for key, _ in os.environ.items()):
    logger.debug("=" * 80)
    logger.debug("%s Django settings overrides %s", "=" * (40 - 13), "=" * (40 - 14))
    logger.debug("=" * 80)
for key, value in os.environ.items():
    if not key.startswith("DJANGO_"):
        continue
    if key == "DJANGO_SETTINGS_MODULE":
        continue

    # Remove the "DJANGO_" prefix to get the actual Django setting name
    key = key.upper().replace("DJANGO_", "")

    # Remove any ASCII control characters from the value to prevent issues with
    # non-printable characters in environment variables, which can sometimes
    # occur due to copy-paste errors or other issues. This is a common source
    # of hard-to-debug problems with environment variable configuration.
    value = ASCII_CONTROL_CHAR_REGEX.sub("", str(value).strip())
    logger.debug("%s Processing Django setting override: %s", logger_prefix, key)

    # If the environment variable does not match any existing Django setting,
    # analyze the value passed to attempt to infer the intended data type the value.
    # This allows for dynamic creation of new settings from environment variables,
    # which can be useful for custom or third-party app configuration without
    # needing to modify the settings file.
    if key not in globals():
        logger.debug(
            formatted_text(
                "%s Environment variable %s does not match any existing Django setting. Inspecting the value to attempt to determine its intended type and usage: %s=%s"
            ),
            logger_prefix,
            key,
            key,
            value,
        )

        raw_value = value
        cast_value = None

        # Ideally, we'd like to leverage the built-in ast.literal_eval()
        # function to safely evaluate string representations of Python
        # literals (e.g. lists, dicts, numbers, booleans) in environment
        # variables. However, this can be problematic if the value is a
        # string that just happens to look like a Python literal
        # (e.g. a string that looks like a list or dict). Therefore, we will
        # attempt to use ast.literal_eval() but fall back to other inference
        # methods if it fails or if the result is not a valid type.
        try:
            cast_value = ast.literal_eval(raw_value) if isinstance(raw_value, str) else raw_value
            logger.debug(
                "%s Successfully cast value using ast.literal_eval() for %s=%s of Type '%s'",
                logger_prefix,
                key,
                cast_value,
                type(cast_value).__name__,
            )
        except (ValueError, SyntaxError):
            cast_value = None

        # Attempt to find Django's default value inside of Python's global
        # namespace and use it to infer the intended type of the environment
        # variable value.
        if not cast_value and globals().get(key) is not None:
            default_value = globals()[key]
            cast_value = smart_cast(raw_value, default_value)
            logger.debug(
                "%s Inferred type '%s' for %s=%s based on existing Django setting default value",
                logger_prefix,
                type(default_value).__name__,
                key,
                cast_value,
            )

        # Hereon, we're simply trying to infer the intended type of the
        # environment variable value based on common patterns and heuristics,
        # since we have no existing Django setting to use as a reference for
        # type casting. This is inherently error-prone, but can be effective
        # for the most common data types and usage patterns.

        # Integer
        elif not cast_value and str(raw_value).replace(".", "").isdigit():
            try:
                cast_value = int(raw_value)
                logger.debug("%s Inferred type 'int' for %s=%s", logger_prefix, key, cast_value)
            except ValueError:
                try:
                    cast_value = float(raw_value)
                    logger.debug("%s Inferred type 'float' for %s=%s", logger_prefix, key, cast_value)
                except ValueError:
                    cast_value = raw_value
                    logger.warning(
                        "%s could not cast as a numeric value. Falling back to string for %s=%s",
                        logger_prefix,
                        key,
                        cast_value,
                    )
        # Date (ISO format)
        elif not cast_value and re.match(r"^\d{4}-\d{2}-\d{2}$", raw_value):
            try:
                cast_value = datetime.strptime(raw_value, "%Y-%m-%d").date()
                logger.debug("%s Inferred type 'date' for %s=%s", logger_prefix, key, cast_value)
            except ValueError:
                pass

        # List (comma-separated)
        elif not cast_value and "," in raw_value:
            try:
                cast_value = [item.strip() for item in raw_value.split(",")]
                logger.debug("%s Inferred type 'list' for %s=%s", logger_prefix, key, cast_value)
            # pylint: disable=broad-except
            except Exception:
                pass

        # Dict (JSON)
        elif not cast_value and raw_value.startswith("{") and raw_value.endswith("}"):
            try:
                cast_value = json.loads(raw_value)
                logger.debug("%s Inferred type 'dict' for %s=%s", logger_prefix, key, cast_value)
            # pylint: disable=broad-except
            except Exception:
                cast_value = raw_value
        # String (default)
        elif not cast_value:
            cast_value = str(raw_value)
            logger.debug("%s Inferred type 'str' for %s=%s", logger_prefix, key, cast_value)

        globals()[key] = cast_value
        logger.info(
            "%s Creating new Django setting from environment variable: %s=%s of Type '%s'",
            logger_prefix,
            key,
            repr(cast_value),
            type(cast_value),
        )
        continue

    # If the environment variable matches an existing Django setting, cast the
    # value to the same type as the existing setting value and override it.
    default_value = globals()[key]
    cast_value = smart_cast(value, default_value)
    globals()[key] = cast_value
    if smarter_settings.settings_output:
        if key not in [
            "SECRET_KEY",
            "SMTP_PASSWORD",
            "SMTP_USERNAME",
            "AWS_ACCESS_KEY_ID",
            "AWS_SECRET_ACCESS_KEY",
        ]:
            logger.info(
                "%s Overriding Django setting from environment variable: %s=%s",
                logger_prefix,
                key,
                repr(cast_value),
            )
        else:
            logger.info(
                "%s Overriding Django setting from environment variable: %s=******",
                logger_prefix,
                key,
            )

###############################################################################
# Settings diagnostics information for all environments
###############################################################################
if smarter_settings.settings_output or "manage.py" not in sys.argv[0]:
    logger.debug("=" * 80)
    logger.debug("%s Settings diagnostics information %s", "=" * (40 - 17), "=" * (40 - 18))
    logger.debug("=" * 80)
    logger.debug("%s Django settings module: %s", logger_prefix, os.environ.get("DJANGO_SETTINGS_MODULE"))

    try:
        with open("/proc/uptime", encoding="utf-8") as f:
            uptime_seconds = float(f.readline().split()[0])
            uptime_str = time.strftime("%H:%M:%S", time.gmtime(uptime_seconds))
            logger.debug("Container uptime: %s", uptime_str)
    except FileNotFoundError:
        logger.warning("Container uptime not available")
    except OSError as e:
        logger.error("Error reading container uptime: %s", e)

    try:
        # CPU limit (cgroup v2)
        cpu_limit = None
        cpu_max_path = "/sys/fs/cgroup/cpu.max"
        if os.path.exists(cpu_max_path):
            with open(cpu_max_path, encoding="utf-8") as f:
                quota, period = f.read().strip().split()
                if quota != "max":
                    cpu_limit = math.ceil(int(quota) / int(period))
                else:
                    cpu_limit = int(subprocess.check_output("nproc", shell=True).decode().strip())
        else:
            cpu_limit = int(subprocess.check_output("nproc", shell=True).decode().strip())

        # Memory limit (cgroup v2)
        mem_limit = None
        mem_max_path = "/sys/fs/cgroup/memory.max"
        if os.path.exists(mem_max_path):
            with open(mem_max_path, encoding="utf-8") as f:
                mem_bytes = int(f.read().strip())
                if mem_bytes < 1 << 60:  # If not unlimited
                    mem_gib = mem_bytes / 1024 / 1024 / 1024
                    mem_limit = mem_gib
                else:
                    # Fallback to /proc/meminfo
                    mem_total_line = subprocess.check_output("grep MemTotal /proc/meminfo", shell=True).decode().strip()
                    mem_kib = int(mem_total_line.split()[1])
                    mem_limit = mem_kib / 1024 / 1024
        else:
            mem_total_line = subprocess.check_output("grep MemTotal /proc/meminfo", shell=True).decode().strip()
            mem_kib = int(mem_total_line.split()[1])
            mem_limit = mem_kib / 1024 / 1024

        logger.debug("CPU limit: %s cores", cpu_limit)
        if cpu_limit < 2:
            logger.warning("Recommended minimum CPU limit is 2. Detected: %s cores", cpu_limit)
        logger.debug("Memory limit: %.2f GiB", mem_limit)
        if mem_limit < 4.0:
            logger.warning("Recommended minimum memory limit is 4 GiB. Detected: %.2f GiB", mem_limit)
    except (OSError, subprocess.CalledProcessError) as e:
        logger.warning("Resource limits not available: %s", e)
    except (ValueError, IndexError) as e:
        logger.error("Error parsing resource limits: %s", e)

    try:
        debian_version = "not found"
        with open("/etc/debian_version", encoding="utf-8") as f:
            debian_version = f.read().strip()
        logger.debug("Debian v%s %s", debian_version, os.uname().version)
    except FileNotFoundError:
        logger.error("Debian version file not found")
    except OSError as e:
        logger.error("Error reading Debian version: %s", e)

    logger.debug("Python v%s", sys.version)
    from django import get_version

    logger.debug("Django v%s", get_version())
    logger.debug("Smarter v%s", smarter_version)
    logger.debug("Default file storage: %s", DEFAULT_FILE_STORAGE)
    logger.debug("Storages backend: %s", STORAGES["default"]["BACKEND"])

    if smarter_settings.smtp_is_configured:
        logger.debug("SMTP server configured: %s:%s (SSL=%s, TLS=%s)", SMTP_HOST, SMTP_PORT, SMTP_USE_SSL, SMTP_USE_TLS)
    else:
        logger.warning("SMTP server not configured")
    if smarter_settings.aws_is_configured:
        logger.debug("AWS credentials detected")
    else:
        logger.warning("AWS credentials not found.")
    logger.debug("=" * 80)

__all__ = [
    name
    for name, value in globals().items()
    if name.isupper()
    and not name.startswith("_")
    and not hasattr(value, "__file__")
    and not callable(value)
    and value is not sys.modules[__name__]
]  # type: ignore[reportUnsupportedDunderAll]
