# pylint: disable=all
# Generated by Django 6.0.5 on 2026-06-08 19:42

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.apps.llm_client.models.llm_client
import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("drf", "0003_alter_smarterauthtoken_tags_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMClientCustomDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("aws_hosted_zone_id", models.CharField(max_length=255)),
                ("domain_name", models.CharField(max_length=255)),
                (
                    "is_verified",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "LLMClient Custom Domains",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="LLMClientRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "request",
                    models.JSONField(
                        blank=True,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "is_aggregation",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "LLMClient Requests History",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="LLMClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                ("deployed", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        default="openai",
                        max_length=255,
                        null=True,
                        validators=[smarter.apps.llm_client.models.llm_client.validate_provider],
                    ),
                ),
                (
                    "default_model",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "default_system_role",
                    models.TextField(
                        blank=True,
                        default="You are a helpful llm_client. When given the opportunity to utilize function calling, you should always do so. This will allow you to provide the best possible responses to the user. If you are unable to provide a response, you should prompt the user for more information. If you are still unable to provide a response, you should inform the user that you are unable to help them at this time.",
                        null=True,
                    ),
                ),
                (
                    "default_temperature",
                    models.FloatField(blank=True, default=0.5, null=True),
                ),
                (
                    "default_max_tokens",
                    models.IntegerField(blank=True, default=2048, null=True),
                ),
                (
                    "app_name",
                    models.CharField(blank=True, default="llm_client", max_length=255, null=True),
                ),
                (
                    "app_assistant",
                    models.CharField(blank=True, default="Smarter", max_length=255, null=True),
                ),
                (
                    "app_welcome_message",
                    models.CharField(
                        blank=True,
                        default="Welcome to the llm_client!",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "app_example_prompts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "app_placeholder",
                    models.CharField(
                        blank=True,
                        default="Type something here...",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "app_info_url",
                    models.URLField(blank=True, default="https://smarter.sh", null=True),
                ),
                ("app_background_image_url", models.URLField(blank=True, null=True)),
                ("app_logo_url", models.URLField(blank=True, null=True)),
                (
                    "app_file_attachment",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "dns_verification_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Verifying", "Verifying"),
                            ("Not Verified", "Not Verified"),
                            ("Verified", "Verified"),
                            ("Failed", "Failed"),
                        ],
                        default="Not Verified",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tls_certificate_issuance_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("No Certificate", "No Certificate"),
                            ("Requested", "Requested"),
                            ("Issued", "Issued"),
                            ("Failed", "Failed"),
                        ],
                        default="No Certificate",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
                (
                    "custom_domain",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_client.llmclientcustomdomain",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LLMClients",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="LLMClientAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drf.smarterauthtoken",
                    ),
                ),
                (
                    "llm_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_client.llmclient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LLMClient API Keys",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="LLMClientCustomDomainDNS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("record_name", models.CharField(max_length=255)),
                ("record_type", models.CharField(max_length=255)),
                ("record_value", models.CharField(max_length=255)),
                ("record_ttl", models.IntegerField(blank=True, default=600, null=True)),
                (
                    "custom_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_client.llmclientcustomdomain",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LLMClient Custom Domain DNS",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.AddField(
            model_name="llmclient",
            name="subdomain",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="llm_client.llmclientcustomdomaindns",
            ),
        ),
        migrations.CreateModel(
            name="LLMClientFunctions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("get_current_weather", "get_current_weather"),
                            ("date_calculator", "date_calculator"),
                            ("calculator", "calculator"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "llm_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_client.llmclient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LLMClient Functions",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="LLMClientPlugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "llm_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_client.llmclient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LLMClient Plugins",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
