---
#------------------------------------------------------------------------------
# For local development, you can use the following docker-compose file
# to run the application. This file will start a MySQL database, a Redis
# server, Celery and Beat workers, and the application itself. The application
# will be available at http://localhost:9357.
#------------------------------------------------------------------------------
services:
  smarter-mysql:
    container_name: smarter-mysql
    mem_limit: 2g
    cpus: 0.5
    image: mysql:8
    command: ["mysqld", "--mysql-native-password=ON"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: smarter
      MYSQL_DATABASE: smarter
      MYSQL_USER: smarter
      MYSQL_PASSWORD: smarter
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  smarter-redis:
    container_name: smarter-redis
    cpus: 0.25
    mem_limit: 1g
    image: redis:latest
    command: redis-server --requirepass smarter
    ports:
      - 6379:6379

  smarter-app:
    container_name: smarter-app
    mem_limit: 4g
    cpus: 1
    user: smarter_user
    x-build:
      type: docker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # future use. The worker and beat services use the same Dockerfile as this app service,
        # but we can optionally set the SCHEMA build argument to something other than "APP"
        # in order to fine tune the build requirements.
        SCHEMA: APP
        ENVIRONMENT: ${ENVIRONMENT}
        DOCKER_COLLECT_STATIC_FILES: ${DOCKER_COLLECT_STATIC_FILES}
        DOCKER_REACT_REMOTE_CACHE_BUSTER: ${DOCKER_REACT_REMOTE_CACHE_BUSTER}
        DOCKER_REACT_REMOTE_CDN_URL: ${DOCKER_REACT_REMOTE_CDN_URL}
    image: smarter
    command: watchmedo auto-restart --directory=./smarter --pattern=*.py --recursive -- uvicorn smarter.asgi:application --host 0.0.0.0 --port 9357
    # volumes:
    #   - type: bind
    #     source: ./smarter
    #     target: /smarter
    #     consistency: cached
    ports:
      - 9357:9357
    depends_on:
      - smarter-mysql
      - smarter-redis
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
      - SERVICE_TYPE=app

  smarter-worker:
    container_name: smarter-worker
    mem_limit: 2g
    cpus: 0.5
    user: smarter_user
    x-build:
      type: docker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # future use. The worker and beat services use the same Dockerfile as the app service,
        # but we can optionally set the SCHEMA build argument to something other than "APP"
        # in order to fine tune the build requirements.
        SCHEMA: APP
        ENVIRONMENT: ${ENVIRONMENT}
        DOCKER_COLLECT_STATIC_FILES: ${DOCKER_COLLECT_STATIC_FILES}
        DOCKER_REACT_REMOTE_CACHE_BUSTER: ${DOCKER_REACT_REMOTE_CACHE_BUSTER}
        DOCKER_REACT_REMOTE_CDN_URL: ${DOCKER_REACT_REMOTE_CDN_URL}
    image: smarter
    command: celery -A smarter.workers.celery.app worker --concurrency=4 --loglevel=info -Q default_celery_task_queue -E
    depends_on:
      - smarter-mysql
      - smarter-redis
      - smarter-app
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
      - SERVICE_TYPE=worker
    # volumes:
    #   - type: bind
    #     source: ./smarter
    #     target: /smarter
    #     consistency: cached
    healthcheck:
      test: ["CMD", "celery", "-A", "smarter.workers.celery.app", "inspect", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  smarter-beat:
    container_name: smarter-beat
    mem_limit: 1g
    cpus: 0.5
    user: smarter_user
    x-build:
      type: docker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # future use. The worker and beat services use the same Dockerfile as the app service,
        # but we can optionally set the SCHEMA build argument to something other than "APP"
        # in order to fine tune the build requirements.
        SCHEMA: APP
        ENVIRONMENT: ${ENVIRONMENT}
        DOCKER_COLLECT_STATIC_FILES: ${DOCKER_COLLECT_STATIC_FILES}
        DOCKER_REACT_REMOTE_CACHE_BUSTER: ${DOCKER_REACT_REMOTE_CACHE_BUSTER}
        DOCKER_REACT_REMOTE_CDN_URL: ${DOCKER_REACT_REMOTE_CDN_URL}
    image: smarter
    command: celery -A smarter.workers.celerybeat.app beat --loglevel=info
    depends_on:
      - smarter-mysql
      - smarter-redis
      - smarter-app
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
      - SERVICE_TYPE=beat
    # volumes:
    #   - type: bind
    #     source: ./smarter
    #     target: /smarter
    #     consistency: cached
    healthcheck:
      test: ["CMD", "celery", "-A", "smarter.workers.celerybeat.app", "inspect", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
