# -----------------------------------------------------------------------------------
# Purpose: CronJob to perform scheduled MySQL database backups to S3.
#
# This file defines a Kubernetes CronJob that runs a backup script
# to back up the MySQL database. The backup script is stored in a
# ConfigMap and mounted into the Job. The Job runs on a Debian image,
# installs necessary tools, and executes the backup script.
#
# Note:
# The app.kubernetes.io/application-group label is used to identify pods to Calico
# and kubernetes_network_policy_v1 resources in order to allow pod-level communication
# between backing services. If the label is missing then the network policies are
# assured to PREVENT communication.
# -----------------------------------------------------------------------------------
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.global.appName }}-mysql-backup"
  namespace: "{{ .Values.namespace }}"
  annotations:
    meta.helm.sh/release-name: "{{ .Values.global.appName }}"
    meta.helm.sh/release-namespace: "{{ .Values.namespace }}"
    meta.helm.sh/application-version: "{{ .Chart.Version }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: "{{ .Values.global.appName }}-mysql-backup"
    app.kubernetes.io/application-group: "{{ .Values.global.appName }}"
spec:
  schedule: {{ .Values.databaseScheduledBackup.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          affinity:
            {{- toYaml .Values.global.affinity | nindent 12 }}
          tolerations:
            {{- toYaml .Values.global.tolerations | nindent 12 }}

          volumes:
            - name: debian-setup-script
              configMap:
                name: debian-setup-script
                defaultMode: 0755
            - name: mysql-backup-script
              configMap:
                name: mysql-backup-script
                defaultMode: 0755

          containers:
            - name: mysql-backup
              image: debian:bullseye-slim
              workingDir: /home/
              command:
                - /bin/bash
                - -c
                - |
                    set -e

                    echo "Waiting for configMap mounts..."
                    for i in $(seq 1 10); do
                      if [ -f /home/setup/install.sh ]; then break; fi
                      echo "Still waiting..."
                      sleep 1
                    done

                    ls -l /home/setup || true
                    ls -l /home/backup || true

                    /home/setup/install.sh
                    /home/backup/backup-to-s3.sh

                    echo "Backup completed successfully!"

              imagePullPolicy: {{ .Values.global.image.pullPolicy | default "Always" }}

              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 250m
                  memory: 512Mi
              volumeMounts:
                - name: debian-setup-script
                  mountPath: /home/setup/install.sh
                  subPath: install.sh
                - name: mysql-backup-script
                  mountPath: /home/backup/backup-to-s3.sh
                  subPath: backup-to-s3.sh

              env:
                {{- range $key, $value := .Values.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- range $env := .Values.app.env }}
                - name: {{ $env.name }}
                  value: {{ $env.value | quote }}
                {{- end }}

          restartPolicy: OnFailure
