# pylint: disable=all
# Generated by Django 6.0.5 on 2026-06-08 19:42

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("connection", "0002_initial"),
        ("provider", "0002_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorestoreMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("qdrant", "qdrant"),
                            ("weaviate", "weaviate"),
                            ("pinecone", "pinecone"),
                        ],
                        help_text="The backend type for the vector database (e.g., qdrant, weaviate, pinecone).",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Indicates whether the vector database is active.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("deleting", "Deleting"),
                        ],
                        default="provisioning",
                        help_text="The current status of the vector database (e.g., provisioning, ready, failed, deleting).",
                        max_length=50,
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Smarter Connection object containing connection details for the vector database. If provided, this connection will be used instead of the host, port, auth_config, and password fields to establish the connection. The Connection object must be owned by the authenticated API user and must contain the necessary information to connect to the vector database.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vector_databases",
                        to="connection.apiconnection",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vectorstore Metadata",
                "verbose_name_plural": "Vectorstore Metadata",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="IndexModelInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "spec",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Index deployment spec. Accepts a dict, ServerlessSpec, PodSpec, or ByocSpec. Example: ServerlessSpec(cloud=CloudProvider.AWS, region=AwsRegion.US_EAST_1)",
                        null=True,
                    ),
                ),
                (
                    "dimension",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Number of dimensions for the index. Must be between 1 and 20,000, or None. Example: 1536.",
                        null=True,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        blank=True,
                        default="cosine",
                        help_text="Distance metric for similarity search. Accepts Metric enum or string. Default: 'cosine'.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Timeout in seconds for index operations. Must be greater than zero or None.",
                        null=True,
                    ),
                ),
                (
                    "deletion_protection",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Deletion protection setting. Accepts DeletionProtection enum or string. Default: 'disabled'.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "vector_type",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Type of vector. Accepts VectorType enum or string. Default: 'dense'.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "vectorestore_meta",
                    models.OneToOneField(
                        help_text="The associated VectorestoreMeta object for this IndexModelInterface configuration.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_model_interface",
                        to="vectorstore.vectorestoremeta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Index Model Interface",
                "verbose_name_plural": "Index Model Interfaces",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="EmbeddingsInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional configuration settings for the embeddings interface.",
                        null=True,
                    ),
                ),
                (
                    "dimensions",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of embedding dimensions.",
                        null=True,
                    ),
                ),
                (
                    "deployment",
                    models.CharField(
                        blank=True,
                        help_text="Deployment name or model name.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "api_version",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI API version.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True,
                        help_text="Base URL for OpenAI API.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "openai_api_type",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI API type.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "openai_api_proxy",
                    models.CharField(
                        blank=True,
                        help_text="Proxy URL for OpenAI API.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "embedding_ctx_length",
                    models.IntegerField(
                        blank=True,
                        default=8191,
                        help_text="Embedding context length.",
                        null=True,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI API key or secret reference.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI organization ID.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "allowed_special",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Allowed special tokens (set[str] or 'all').",
                        null=True,
                    ),
                ),
                (
                    "disallowed_special",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Disallowed special tokens (set, sequence, or 'all').",
                        null=True,
                    ),
                ),
                (
                    "chunk_size",
                    models.IntegerField(
                        blank=True,
                        default=1000,
                        help_text="Chunk size for embedding requests.",
                        null=True,
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        blank=True,
                        default=2,
                        help_text="Maximum number of retries for API calls.",
                        null=True,
                    ),
                ),
                (
                    "timeout",
                    models.FloatField(
                        blank=True,
                        help_text="Timeout for API requests (float, tuple, or other).",
                        null=True,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom headers for API requests.",
                        null=True,
                    ),
                ),
                (
                    "tiktoken_enabled",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Enable tiktoken for tokenization.",
                        null=True,
                    ),
                ),
                (
                    "tiktoken_model_name",
                    models.CharField(
                        blank=True,
                        help_text="Tiktoken model name.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "show_progress_bar",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Show progress bar during embedding.",
                        null=True,
                    ),
                ),
                (
                    "model_kwargs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional model keyword arguments.",
                        null=True,
                    ),
                ),
                (
                    "skip_empty",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Skip empty inputs.",
                        null=True,
                    ),
                ),
                (
                    "default_headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default headers for API requests.",
                        null=True,
                    ),
                ),
                (
                    "default_query",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default query parameters for API requests.",
                        null=True,
                    ),
                ),
                (
                    "retry_min_seconds",
                    models.IntegerField(
                        blank=True,
                        default=4,
                        help_text="Minimum seconds between retries.",
                        null=True,
                    ),
                ),
                (
                    "retry_max_seconds",
                    models.IntegerField(
                        blank=True,
                        default=20,
                        help_text="Maximum seconds between retries.",
                        null=True,
                    ),
                ),
                (
                    "check_ctx_length",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Check embedding context length.",
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="The provider associated with this vector database.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_databases",
                        to="provider.provider",
                    ),
                ),
                (
                    "provider_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="The provider model associated with this vector database.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vector_databases",
                        to="provider.providermodel",
                    ),
                ),
                (
                    "vectorestore_meta",
                    models.OneToOneField(
                        help_text="The associated VectorestoreMeta object for this EmbeddingsInterface configuration.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings_interface",
                        to="vectorstore.vectorestoremeta",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="VectorstoreInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "text_key",
                    models.CharField(
                        blank=True,
                        help_text="The key in the vector database where the original text is stored, if applicable.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True,
                        help_text="The namespace to use for the vector database, if applicable.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "distance_strategy",
                    models.CharField(
                        blank=True,
                        help_text="The distance strategy to use for similarity search (e.g., cosine, euclidean, dot_product), if applicable.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "vectorestore_meta",
                    models.OneToOneField(
                        help_text="The associated VectorestoreMeta object for this VectorstoreInterface configuration.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vectorstore_interface",
                        to="vectorstore.vectorestoremeta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vectorstore Interface",
                "verbose_name_plural": "Vectorstore Interfaces",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
