# pylint: disable=all
# Generated by Django 6.0.5 on 2026-06-08 19:42

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SqlConnection", "SqlConnection"),
                            ("ApiConnection", "ApiConnection"),
                        ],
                        help_text="The kind of connection. Example: 'SQL', 'API'.",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="ApiConnection",
            fields=[
                (
                    "connectionbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="connection.connectionbase",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(help_text="The root domain of the API. Example: 'https://api.example.com'."),
                ),
                (
                    "auth_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("basic", "Basic Auth"),
                            ("token", "Token Auth"),
                            ("oauth", "OAuth"),
                        ],
                        default="none",
                        help_text="The authentication method to use. Example: 'Basic Auth', 'Token Auth'.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        blank=True,
                        default=30,
                        help_text="The timeout for the API request in seconds. Default is 30 seconds.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "proxy_protocol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("http", "HTTP"),
                            ("https", "HTTPS"),
                            ("socks", "SOCKS"),
                        ],
                        default="http",
                        help_text="The protocol to use for the proxy connection.",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("proxy_host", models.CharField(blank=True, max_length=255, null=True)),
                ("proxy_port", models.IntegerField(blank=True, null=True)),
                (
                    "proxy_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "API Connection",
                "verbose_name_plural": "API Connections",
            },
            bases=("connection.connectionbase",),
        ),
        migrations.CreateModel(
            name="SqlConnection",
            fields=[
                (
                    "connectionbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="connection.connectionbase",
                    ),
                ),
                (
                    "db_engine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("django.db.backends.mysql", "django.db.backends.mysql"),
                            (
                                "django.db.backends.postgresql",
                                "django.db.backends.postgresql",
                            ),
                            (
                                "django.db.backends.sqlite3",
                                "django.db.backends.sqlite3",
                            ),
                            ("django.db.backends.oracle", "django.db.backends.oracle"),
                            ("django.db.backends.mssql", "django.db.backends.mssql"),
                            ("django.db.backends.sybase", "django.db.backends.sybase"),
                        ],
                        default="django.db.backends.mysql",
                        help_text="The type of database management system. Example: 'MySQL', 'PostgreSQL', 'MS SQL Server', 'Oracle'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "authentication_method",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("tcpip", "Tcpip"),
                            ("tcpip_ssh", "Tcpip Ssh"),
                            ("ldap_user_pwd", "Ldap User Pwd"),
                        ],
                        default="tcpip",
                        help_text="The authentication method to use for the connection. Example: 'Standard TCP/IP', 'Standard TCP/IP over SSH', 'LDAP User/Password'.",
                        max_length=255,
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        blank=True,
                        default=30,
                        help_text="The timeout for the database connection in seconds. Default is 30 seconds.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "use_ssl",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Whether to use SSL/TLS for the connection.",
                        null=True,
                    ),
                ),
                (
                    "ssl_cert",
                    models.TextField(
                        blank=True,
                        help_text="The SSL certificate for the connection, if required.",
                        null=True,
                    ),
                ),
                (
                    "ssl_key",
                    models.TextField(
                        blank=True,
                        help_text="The SSL key for the connection, if required.",
                        null=True,
                    ),
                ),
                (
                    "ssl_ca",
                    models.TextField(
                        blank=True,
                        help_text="The Certificate Authority (CA) certificate for verifying the server.",
                        null=True,
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        help_text="The remote host of the SQL connection. Should be a valid internet domain name.",
                        max_length=255,
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True,
                        default=3306,
                        help_text="The port of the SQL connection. example: 3306 for MySQL.",
                        null=True,
                    ),
                ),
                (
                    "database",
                    models.CharField(
                        help_text="The name of the database to connect to.",
                        max_length=255,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="The database username.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pool_size",
                    models.IntegerField(
                        blank=True,
                        default=5,
                        help_text="The size of the connection pool.",
                        null=True,
                    ),
                ),
                (
                    "max_overflow",
                    models.IntegerField(
                        blank=True,
                        default=10,
                        help_text="The maximum number of connections to allow beyond the pool size.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "proxy_protocol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("http", "HTTP"),
                            ("https", "HTTPS"),
                            ("socks", "SOCKS"),
                        ],
                        default="http",
                        help_text="The protocol to use for the proxy connection.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "proxy_host",
                    models.CharField(
                        blank=True,
                        help_text="The remote host of the SQL proxy connection. Should be a valid internet domain name.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "proxy_port",
                    models.IntegerField(
                        blank=True,
                        help_text="The port of the SQL proxy connection.",
                        null=True,
                    ),
                ),
                (
                    "proxy_username",
                    models.CharField(
                        blank=True,
                        help_text="The username for the proxy connection.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ssh_known_hosts",
                    models.TextField(
                        blank=True,
                        help_text="The known_hosts file content for verifying SSH connections. Usually comes from ~/.ssh/known_hosts.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "SQL Connection",
                "verbose_name_plural": "SQL Connections",
            },
            bases=("connection.connectionbase",),
        ),
    ]
