# pylint: disable=all
# Generated by Django 6.0.5 on 2026-06-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("connection", "0001_initial"),
        ("secret", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconnection",
            name="api_key",
            field=models.ForeignKey(
                blank=True,
                help_text="The API key for authentication, if required.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_connections_api_key",
                to="secret.secret",
            ),
        ),
        migrations.AddField(
            model_name="apiconnection",
            name="proxy_password",
            field=models.ForeignKey(
                blank=True,
                help_text="The proxy password for authentication, if required.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_connections_proxy_password",
                to="secret.secret",
            ),
        ),
        migrations.AddField(
            model_name="sqlconnection",
            name="password",
            field=models.ForeignKey(
                blank=True,
                help_text="The password for authentication, if required.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sql_connections_password",
                to="secret.secret",
            ),
        ),
        migrations.AddField(
            model_name="sqlconnection",
            name="proxy_password",
            field=models.ForeignKey(
                blank=True,
                help_text="The API key for authentication, if required.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sql_connections_proxy_password",
                to="secret.secret",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connectionbase",
            unique_together={("user_profile", "name")},
        ),
    ]
