# pylint: disable=all
# Generated by Django 6.0.4 on 2026-05-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf", "0002_alter_smarterauthtoken_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smarterauthtoken",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name="StringPKTaggedItem",
        ),
    ]
