"""
Enhanced logging features for Smarter, including Waffle switch-controlled
loggers and custom Redis and Streaming file handlers.
"""

from logging import (
    BASIC_FORMAT,
    CRITICAL,
    DEBUG,
    ERROR,
    FATAL,
    INFO,
    NOTSET,
    WARN,
    WARNING,
    BufferingFormatter,
    FileHandler,
    Filter,
    Formatter,
    Handler,
    Logger,
    LoggerAdapter,
    LogRecord,
    NullHandler,
    StreamHandler,
    addLevelName,
    basicConfig,
    captureWarnings,
    critical,
    debug,
    disable,
    error,
    exception,
    fatal,
    getHandlerByName,
    getHandlerNames,
    getLevelName,
    getLevelNamesMapping,
    getLogger,
    getLoggerClass,
    getLogRecordFactory,
    info,
    lastResort,
    log,
    makeLogRecord,
    raiseExceptions,
    setLoggerClass,
    setLogRecordFactory,
    shutdown,
    warn,
    warning,
)

from smarter.common.helpers.console_helpers import (
    formatted_json,
    formatted_text,
    formatted_text_blue,
    formatted_text_green,
    formatted_text_red,
)

from .get_smarter_logger import getSmarterLogger
from .redis_log_handler import (
    GLOBAL_LOG_CHANNEL,
    RedisLogHandler,
    build_channel,
    get_user_context,
    job_id_factory,
    user_id_context,
)
from .streaming_file_handler import StreamingFileHandler
from .waffle_switched_logger import WaffleSwitchedLoggerWrapper

__all__ = [
    "get_user_context",
    "WaffleSwitchedLoggerWrapper",
    "build_channel",
    "user_id_context",
    "job_id_factory",
    "StreamingFileHandler",
    "RedisLogHandler",
    "GLOBAL_LOG_CHANNEL",
    "BASIC_FORMAT",
    "BufferingFormatter",
    "CRITICAL",
    "DEBUG",
    "ERROR",
    "FATAL",
    "FileHandler",
    "Filter",
    "Formatter",
    "Handler",
    "INFO",
    "LogRecord",
    "Logger",
    "LoggerAdapter",
    "NOTSET",
    "NullHandler",
    "StreamHandler",
    "WARN",
    "WARNING",
    "addLevelName",
    "basicConfig",
    "captureWarnings",
    "critical",
    "debug",
    "disable",
    "error",
    "formatted_text",
    "formatted_json",
    "formatted_text_blue",
    "formatted_text_green",
    "formatted_text_red",
    "exception",
    "fatal",
    "getLevelName",
    "getLogger",
    "getLoggerClass",
    "info",
    "log",
    "makeLogRecord",
    "setLoggerClass",
    "shutdown",
    "warn",
    "warning",
    "getLogRecordFactory",
    "setLogRecordFactory",
    "lastResort",
    "raiseExceptions",
    "getLevelNamesMapping",
    "getHandlerByName",
    "getHandlerNames",
]
