# pylint: disable=all
# Generated by Django 6.0.5 on 2026-06-08 19:42

from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verifying", "Verifying"),
                            ("failed", "Verification Failed"),
                            ("verified", "Verified"),
                            ("suspended", "Suspended"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="unverified",
                        max_length=32,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_deprecated", models.BooleanField(default=False)),
                ("is_flagged", models.BooleanField(default=False)),
                ("is_suspended", models.BooleanField(default=False)),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="The base URL for the provider's API.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "default_model",
                    models.CharField(
                        blank=True,
                        help_text="The default model to use for the provider.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "connectivity_test_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The URL to test connectivity with the provider's API.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="The logo of the provider.",
                        null=True,
                        upload_to="provider/provider_logos/",
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        help_text="The website_url URL of the provider.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ownership_requested",
                    models.EmailField(
                        blank=True,
                        help_text="The email address of an alternative contact who has requested to take ownership of the provider.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="The contact email of the provider.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_email_verified",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when the contact email was verified.",
                        null=True,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        help_text="The support email of the provider.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "support_email_verified",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when the support email was verified.",
                        null=True,
                    ),
                ),
                (
                    "docs_url",
                    models.URLField(
                        blank=True,
                        help_text="The documentation URL of the provider.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "terms_of_service_url",
                    models.URLField(
                        blank=True,
                        help_text="The terms of service URL of the provider.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "privacy_policy_url",
                    models.URLField(
                        blank=True,
                        help_text="The privacy policy URL of the provider.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tos_accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when the terms of service were accepted.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="ProviderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_deprecated", models.BooleanField(default=False)),
                ("is_flagged", models.BooleanField(default=False)),
                ("is_suspended", models.BooleanField(default=False)),
                ("max_completion_tokens", models.PositiveIntegerField(default=4096)),
                ("temperature", models.FloatField(default=0.7)),
                ("top_p", models.FloatField(default=1.0)),
                ("supports_text_input", models.BooleanField(default=True)),
                ("supports_text_generation", models.BooleanField(default=True)),
                ("supports_translation", models.BooleanField(default=True)),
                ("supports_summarization", models.BooleanField(default=True)),
                ("supports_streaming", models.BooleanField(default=False)),
                ("supports_tools", models.BooleanField(default=False)),
                ("supports_image_input", models.BooleanField(default=False)),
                ("supports_audio_input", models.BooleanField(default=False)),
                ("supports_embedding", models.BooleanField(default=False)),
                ("supports_fine_tuning", models.BooleanField(default=False)),
                ("supports_search", models.BooleanField(default=False)),
                ("supports_code_interpreter", models.BooleanField(default=False)),
                ("supports_image_generation", models.BooleanField(default=False)),
                ("supports_audio_generation", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Provider Model",
                "verbose_name_plural": "Provider Models",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="ProviderModelVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("streaming", "Streaming"),
                            ("tools", "Tools"),
                            ("text_input", "Text Input"),
                            ("image_input", "Image Input"),
                            ("audio_input", "Audio Input"),
                            ("fine_tuning", "Fine Tuning"),
                            ("search", "Search"),
                            ("code_interpreter", "Code Interpreter"),
                            ("text_to_image", "Text to Image"),
                            ("text_to_audio", "Text to Audio"),
                            ("text_to_text", "Text to Text"),
                            ("translation", "Translation"),
                            ("summarization", "Summarization"),
                        ],
                        default="text_input",
                        max_length=32,
                    ),
                ),
                ("is_successful", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Provider Model Verification",
                "verbose_name_plural": "Provider Model Verifications",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="ProviderVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("api_connectivity", "Api Connectivity"),
                            ("logo", "Logo"),
                            ("contact_email", "Contact Email"),
                            ("support_email", "Support Email"),
                            ("website_url", "Website URL"),
                            ("tos_url", "Terms of Service URL"),
                            ("privacy_policy_url", "Privacy Policy URL"),
                            ("tos_acceptance", "Terms of Service Acceptance"),
                            ("production_api_key", "Production API Key"),
                        ],
                        default="api_connectivity",
                        max_length=32,
                    ),
                ),
                ("is_successful", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Provider Verification",
                "verbose_name_plural": "Provider Verifications",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
