# pylint: disable=all
# Generated by Django 6.0.5 on 2026-06-08 19:42

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("provider", "0001_initial"),
        ("secret", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="api_key",
            field=models.ForeignKey(
                blank=True,
                help_text="The API key for the provider.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provider_api_key",
                to="secret.secret",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags for categorizing and organizing this resource.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="tos_accepted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who accepted the terms of service.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tos_accepted_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="user_profile",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="account.userprofile"),
        ),
        migrations.AddField(
            model_name="providermodel",
            name="provider",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="provider.provider"),
        ),
        migrations.AddField(
            model_name="providermodelverification",
            name="provider_model",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="provider.providermodel"),
        ),
        migrations.AddField(
            model_name="providerverification",
            name="provider",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="provider.provider"),
        ),
        migrations.AlterUniqueTogether(
            name="providermodel",
            unique_together={("provider", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="providermodelverification",
            unique_together={("provider_model", "verification_type")},
        ),
        migrations.AlterUniqueTogether(
            name="providerverification",
            unique_together={("provider", "verification_type")},
        ),
    ]
